# Generated by Django 2.1.7 on 2019-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='dificultat',
            field=models.IntegerField(choices=[('D', 'Desconeguda'), ('B', 'Baixa'), ('M', 'Mitjana'), ('A', 'Alta')], default='D'),
        ),
    ]
