# Generated by Django 2.1.7 on 2019-02-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0004_auto_20190218_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='dificultat',
            field=models.CharField(choices=[('D', 'Desconeguda'), ('B', 'Baixa'), ('M', 'Mitjana'), ('A', 'Alta')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='spec',
            name='projecte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cor.Projecte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spec',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cor.Sprint'),
        ),
    ]
